reconciliationPaused: false
version: ""
tenant:
  name: ""
  organizationName: ""
  instanceType: ""
  organizationId: ""
  id: ""
  internal: false
central:
  vpa:
    enabled: true
    recommenders: null
    updatePolicy:
      updateMode: "Auto"
      minReplicas: 1
    resourcePolicy:
      containerPolicies:
        - containerName: "*"
          minAllowed:
            cpu: "100m"
            memory: "250Mi"
          maxAllowed:
            cpu: "1.5"
            memory: "18Gi"
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 10m
      memory: 1000Mi
centralDb:
  connectionString: ""
  caCerts: [ ]
scannerV2:
  resources:
    limits:
      memory: 2750Mi
    requests:
      cpu: 30m
      memory: 2750Mi
scannerV2Db:
  resources:
    limits:
      memory: 1000Mi
    requests:
      cpu: 30m
      memory: 1000Mi
rdsCidrBlock: "10.1.0.0/16"